# Generated by Django 3.2.8 on 2022-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0003_alter_film_slider_slider_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmler',
            name='film_resmi',
            field=models.FileField(upload_to='sayfalar/filmler'),
        ),
    ]
