# Generated by Django 3.2.8 on 2022-05-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0005_deneme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
