# Generated by Django 3.2.8 on 2022-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0007_film_slider_slider_sm_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_slider',
            name='slider_sm_resim',
            field=models.FileField(blank=True, upload_to='filmler/slider', verbose_name='Slider Küçük Resim'),
        ),
    ]
