# Generated by Django 3.2.8 on 2022-05-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0008_alter_film_slider_slider_sm_resim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film_kategorileri',
            new_name='FilmKategorileri',
        ),
        migrations.RenameModel(
            old_name='Film_slider',
            new_name='FilmSlider',
        ),
    ]
