# Generated by Django 3.2.8 on 2022-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0009_auto_20220524_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmler',
            name='film_kategoriler',
            field=models.ManyToManyField(related_name='filmler', to='sayfalar.FilmKategorileri'),
        ),
    ]
