# Generated by Django 3.2.8 on 2022-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0011_auto_20220525_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmler',
            name='film_cikis_tarihi',
        ),
        migrations.AlterField(
            model_name='filmler',
            name='film_adi',
            field=models.CharField(max_length=50, verbose_name='Film Adı'),
        ),
        migrations.AlterField(
            model_name='filmler',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif Film'),
        ),
    ]
